- name: Change default config
  become: yes
  template:
   src: nginx.conf
   dest: /etc/nginx/conf.d/default.conf
  notify: Restart nginx

- name: run nginx
  become: yes
  service:
   name: nginx
   state: started
   enabled: yes
