- name: Change default config
  become: yes
  copy:
   src: ./default.conf
   dest: /etc/nginx/conf.d/default.conf

- name: run nginx
  become: yes
  service:
   name: nginx
   state: restarted
   enabled: yes
