- name: Install nginx
  become: yes
  yum: name=nginx state=latest

- name: Change default config
  become: yes
  template:
   src: nginx.conf
   dest: /etc/nginx/conf.d/default.conf

- name: Restart nginx
  become: yes
  service: name=nginx state=restarted