- name: Install nginx
  become: yes
  yum: name=nginx state=latest
  notify: Restart nginx

- name: Change default config
  become: yes
  template:
   src: nginx.conf
   dest: /etc/nginx/conf.d/default.conf
  register: nginx_conf_result
  
- set_fact:
   is_nginx_config_changed: "{{nginx_conf_result.changed}}"

- name: Restart nginx
  become: yes
  service:
   name: nginx 
   state: restarted
  when: is_nginx_config_changed