- name: Install nginx
  become: yes
  yum: name=nginx state=latest
  register: install_info

- name: Change default config
  become: yes
  template:
   src: nginx.conf
   dest: /etc/nginx/conf.d/default.conf
  register: conf_info

- name: Restart nginx
  become: yes
  service:
   name: nginx 
   state: restarted
  when: conf_info.changed or install_info.changed