---
- hosts: assignmenthosts
  tasks:
   # - name: installing nginx
   #   become: yes
   #   yum:
   #     name: nginx
   #     state: latest
   - name: Add Node js repository
     become: yes
     yum_repository:
      name: nodejs
      description: installing node
      baseurl: https://rpm.nodesource.com/pub_7.x/el/6/x86_64/
      gpgcheck: no

   - name: installing node js
     become: yes
     yum: name={{item}} state=latest
     with_items:
       - nodejs-7.6.0

   # - name: installing nodejs
   #   become: yes
   #   yum:
   #     name: nodejs
