---
- hosts: myhosts
  vars_files:
   - ./vars/hostServer.yml
  roles:
    - nodejs
    - nginx
    
- hosts: assignmenthosts
  vars_files:
    - ./vars/assignmentHost.yml
  roles:
   - nodejs  
  tasks: