---
- hosts: myhosts
  vars:
   node_version: 7.10.0
  tasks:
   - name: include nodejs role
     include_role:
      name: nodejs
   - name: installing nginx and node js
     become: yes
     yum: name=nginx state=latest
     
   - name: Change default config
     become: yes
     copy:
      src: ./default.conf
      dest: /etc/nginx/conf.d/default.conf

   - name: run nginx
     become: yes
     service:
       name: nginx
       state: restarted
       enabled: yes

- hosts: assignmenthosts
  vars:
   node_version: 7.8.0
  tasks:
   - name: include nodejs role
     include_role:
      name: nodejs