---
- hosts: all
  tasks:
   - name: Add Node js repository
     become: yes
     yum_repository:
      name: nodejs
      description: installing node
      baseurl: https://rpm.nodesource.com/pub_7.x/el/6/x86_64/
      gpgcheck: no

- hosts: myhosts
  tasks:
   - name: installing nginx and node js
     become: yes
     yum: name={{item}} state=latest
     with_items:
       - nginx
       - nodejs-7.8.0

   - name: Change default config
     become: yes
     copy:
      src: ./default.conf
      dest: /etc/nginx/conf.d/default.conf

   - name: run nginx
     become: yes
     service:
       name: nginx
       state: restarted
       enabled: yes

- hosts: assignmenthosts
  tasks:
   - name: installing node js
     become: yes
     yum: name={{item}} state=latest
     with_items:
       - nodejs-7.10.0