---
- hosts: myhosts
  vars_files:
   - ./configs/hostServer.yml
  roles:
    - nginx  
    - nodejs

- hosts: assignmenthosts
  vars_files:
    - ./configs/assignmentHost.yml
  roles:
   - nodejs  
  tasks: