- name: Add Node js repository
  become: yes
  yum_repository:
   name: nodejs
   description: installing node
   baseurl: https://rpm.nodesource.com/pub_7.x/el/6/x86_64/
   gpgcheck: no

- debug:
   msg: "{{node_version}}"
- name: installing node js
  become: yes
  yum:
    name: nodejs-{{node_version}}
    state: latest