- name : Adding go server repo
  become: yes
  yum_repository:
   name: go_server
   description: Go-CD repo
   baseurl: https://download.gocd.io
   gpgkey: https://download.gocd.io/GOCD-GPG-KEY.asc
   gpgcheck: yes

- name: Install go server
  become: yes
  yum:
    name: go-server-{{go_server_version}}
    state: present

- name: Start go Server
  become: yes
  service:
    name: go-server
    state: started
